# declare the version
version: "3.8"

#declare the network
networks:
  vote:
    driver: bridge

# declare the services
services:
  # declare the service name
  vote:
    # declare the image
    image: oreakinodidi/voteapp-python
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - 80
    depends_on:
      - redis
  
  redis:
    image: redis:7.0-alpine
    networks:
      - vote
  
  worker:
    image: oreakinodidi/workerapp-maven
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - vote
    depends_on:
      - redis
      - db

  db:
    image: postgres:12-alpine
    networks:
      - vote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  result:
    image: oreakinodidi/resultapp-pynodejsthon
    build:
      context: ./result 
      dockerfile: Dockerfile
    ports:
      - 80
    networks:
      - vote
    depends_on:
      - db