apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: postgres
    role: db
    version: v1
spec:
  containers:
  - name: db
    image: postgres:12-alpine
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    # - name: POSTGRES_USER
    #   value: postgres
    # - name: POSTGRES_PASSWORD
    #   value: password
    ports:
    - containerPort: 5432
      name: db
      protocol: TCP
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-data

  volumes:
  - name: db-data
    hostPath:
      path: /var/lib/pgdata
      type: DirectoryOrCreate